# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protobufs import reports_pb2 as protobufs_dot_reports__pb2


class ReportsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsersRoutesLengthReport = channel.unary_unary(
                '/routes.Reports/GetUsersRoutesLengthReport',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=protobufs_dot_reports__pb2.UserRoutesLengthReportResponse.FromString,
                )


class ReportsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUsersRoutesLengthReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsersRoutesLengthReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersRoutesLengthReport,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=protobufs_dot_reports__pb2.UserRoutesLengthReportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routes.Reports', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Reports(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUsersRoutesLengthReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routes.Reports/GetUsersRoutesLengthReport',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            protobufs_dot_reports__pb2.UserRoutesLengthReportResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
