# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/reports.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/reports.proto',
  package='routes',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17protobufs/reports.proto\x12\x06routes\x1a\x1bgoogle/protobuf/empty.proto\"^\n\x11UserRoutesLengths\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x14\n\x0croutes_count\x18\x02 \x01(\x05\x12\"\n\x1aroutes_total_length_meters\x18\x03 \x01(\x02\"L\n\x1eUserRoutesLengthReportResponse\x12*\n\x07records\x18\x01 \x03(\x0b\x32\x19.routes.UserRoutesLengths2g\n\x07Reports\x12\\\n\x1aGetUsersRoutesLengthReport\x12\x16.google.protobuf.Empty\x1a&.routes.UserRoutesLengthReportResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_USERROUTESLENGTHS = _descriptor.Descriptor(
  name='UserRoutesLengths',
  full_name='routes.UserRoutesLengths',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='routes.UserRoutesLengths.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='routes_count', full_name='routes.UserRoutesLengths.routes_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='routes_total_length_meters', full_name='routes.UserRoutesLengths.routes_total_length_meters', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=158,
)


_USERROUTESLENGTHREPORTRESPONSE = _descriptor.Descriptor(
  name='UserRoutesLengthReportResponse',
  full_name='routes.UserRoutesLengthReportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='routes.UserRoutesLengthReportResponse.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=236,
)

_USERROUTESLENGTHREPORTRESPONSE.fields_by_name['records'].message_type = _USERROUTESLENGTHS
DESCRIPTOR.message_types_by_name['UserRoutesLengths'] = _USERROUTESLENGTHS
DESCRIPTOR.message_types_by_name['UserRoutesLengthReportResponse'] = _USERROUTESLENGTHREPORTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRoutesLengths = _reflection.GeneratedProtocolMessageType('UserRoutesLengths', (_message.Message,), {
  'DESCRIPTOR' : _USERROUTESLENGTHS,
  '__module__' : 'protobufs.reports_pb2'
  # @@protoc_insertion_point(class_scope:routes.UserRoutesLengths)
  })
_sym_db.RegisterMessage(UserRoutesLengths)

UserRoutesLengthReportResponse = _reflection.GeneratedProtocolMessageType('UserRoutesLengthReportResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERROUTESLENGTHREPORTRESPONSE,
  '__module__' : 'protobufs.reports_pb2'
  # @@protoc_insertion_point(class_scope:routes.UserRoutesLengthReportResponse)
  })
_sym_db.RegisterMessage(UserRoutesLengthReportResponse)



_REPORTS = _descriptor.ServiceDescriptor(
  name='Reports',
  full_name='routes.Reports',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=238,
  serialized_end=341,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUsersRoutesLengthReport',
    full_name='routes.Reports.GetUsersRoutesLengthReport',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_USERROUTESLENGTHREPORTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPORTS)

DESCRIPTOR.services_by_name['Reports'] = _REPORTS

# @@protoc_insertion_point(module_scope)
