# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/routes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/routes.proto',
  package='routes',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16protobufs/routes.proto\x12\x06routes\"F\n\x05Point\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\x02\x12\x11\n\tlongitude\x18\x04 \x01(\x02\"D\n\x08WayPoint\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1c\n\x05point\x18\x02 \x01(\x0b\x32\r.routes.Point\x12\x0e\n\x06serial\x18\x03 \x01(\x05\"F\n\x05Route\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12#\n\twaypoints\x18\x03 \x03(\x0b\x32\x10.routes.WayPoint\"%\n\x10GetPointsRequest\x12\x11\n\tpoint_ids\x18\x01 \x03(\x05\"2\n\x11GetPointsResponse\x12\x1d\n\x06points\x18\x01 \x03(\x0b\x32\r.routes.Point\"7\n\x10GetRoutesRequest\x12\x11\n\troute_ids\x18\x01 \x03(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\"2\n\x11GetRoutesResponse\x12\x1d\n\x06routes\x18\x01 \x03(\x0b\x32\r.routes.Route\"?\n\x15\x43\x61lculateRouteRequest\x12\x12\n\na_point_id\x18\x01 \x01(\x05\x12\x12\n\nb_point_id\x18\x02 \x01(\x05\"-\n\rRouteResponse\x12\x1c\n\x05route\x18\x01 \x01(\x0b\x32\r.routes.Route\";\n\x12\x43reateRouteRequest\x12\x11\n\tpoint_ids\x18\x01 \x03(\x05\x12\x12\n\nroute_name\x18\x02 \x01(\t2\x96\x02\n\x06Routes\x12@\n\tGetPoints\x12\x18.routes.GetPointsRequest\x1a\x19.routes.GetPointsResponse\x12@\n\tGetRoutes\x12\x18.routes.GetRoutesRequest\x1a\x19.routes.GetRoutesResponse\x12\x46\n\x0e\x43\x61lculateRoute\x12\x1d.routes.CalculateRouteRequest\x1a\x15.routes.RouteResponse\x12@\n\x0b\x43reateRoute\x12\x1a.routes.CreateRouteRequest\x1a\x15.routes.RouteResponseb\x06proto3'
)




_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='routes.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='routes.Point.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='routes.Point.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='routes.Point.latitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='routes.Point.longitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=104,
)


_WAYPOINT = _descriptor.Descriptor(
  name='WayPoint',
  full_name='routes.WayPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='routes.WayPoint.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point', full_name='routes.WayPoint.point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='serial', full_name='routes.WayPoint.serial', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=174,
)


_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='routes.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='routes.Route.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='routes.Route.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='waypoints', full_name='routes.Route.waypoints', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=246,
)


_GETPOINTSREQUEST = _descriptor.Descriptor(
  name='GetPointsRequest',
  full_name='routes.GetPointsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='point_ids', full_name='routes.GetPointsRequest.point_ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=285,
)


_GETPOINTSRESPONSE = _descriptor.Descriptor(
  name='GetPointsResponse',
  full_name='routes.GetPointsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='routes.GetPointsResponse.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=337,
)


_GETROUTESREQUEST = _descriptor.Descriptor(
  name='GetRoutesRequest',
  full_name='routes.GetRoutesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='route_ids', full_name='routes.GetRoutesRequest.route_ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='routes.GetRoutesRequest.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=394,
)


_GETROUTESRESPONSE = _descriptor.Descriptor(
  name='GetRoutesResponse',
  full_name='routes.GetRoutesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='routes', full_name='routes.GetRoutesResponse.routes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=446,
)


_CALCULATEROUTEREQUEST = _descriptor.Descriptor(
  name='CalculateRouteRequest',
  full_name='routes.CalculateRouteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a_point_id', full_name='routes.CalculateRouteRequest.a_point_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b_point_id', full_name='routes.CalculateRouteRequest.b_point_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=511,
)


_ROUTERESPONSE = _descriptor.Descriptor(
  name='RouteResponse',
  full_name='routes.RouteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='route', full_name='routes.RouteResponse.route', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=558,
)


_CREATEROUTEREQUEST = _descriptor.Descriptor(
  name='CreateRouteRequest',
  full_name='routes.CreateRouteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='point_ids', full_name='routes.CreateRouteRequest.point_ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route_name', full_name='routes.CreateRouteRequest.route_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=560,
  serialized_end=619,
)

_WAYPOINT.fields_by_name['point'].message_type = _POINT
_ROUTE.fields_by_name['waypoints'].message_type = _WAYPOINT
_GETPOINTSRESPONSE.fields_by_name['points'].message_type = _POINT
_GETROUTESRESPONSE.fields_by_name['routes'].message_type = _ROUTE
_ROUTERESPONSE.fields_by_name['route'].message_type = _ROUTE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['WayPoint'] = _WAYPOINT
DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
DESCRIPTOR.message_types_by_name['GetPointsRequest'] = _GETPOINTSREQUEST
DESCRIPTOR.message_types_by_name['GetPointsResponse'] = _GETPOINTSRESPONSE
DESCRIPTOR.message_types_by_name['GetRoutesRequest'] = _GETROUTESREQUEST
DESCRIPTOR.message_types_by_name['GetRoutesResponse'] = _GETROUTESRESPONSE
DESCRIPTOR.message_types_by_name['CalculateRouteRequest'] = _CALCULATEROUTEREQUEST
DESCRIPTOR.message_types_by_name['RouteResponse'] = _ROUTERESPONSE
DESCRIPTOR.message_types_by_name['CreateRouteRequest'] = _CREATEROUTEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'protobufs.routes_pb2'
  # @@protoc_insertion_point(class_scope:routes.Point)
  })
_sym_db.RegisterMessage(Point)

WayPoint = _reflection.GeneratedProtocolMessageType('WayPoint', (_message.Message,), {
  'DESCRIPTOR' : _WAYPOINT,
  '__module__' : 'protobufs.routes_pb2'
  # @@protoc_insertion_point(class_scope:routes.WayPoint)
  })
_sym_db.RegisterMessage(WayPoint)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), {
  'DESCRIPTOR' : _ROUTE,
  '__module__' : 'protobufs.routes_pb2'
  # @@protoc_insertion_point(class_scope:routes.Route)
  })
_sym_db.RegisterMessage(Route)

GetPointsRequest = _reflection.GeneratedProtocolMessageType('GetPointsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPOINTSREQUEST,
  '__module__' : 'protobufs.routes_pb2'
  # @@protoc_insertion_point(class_scope:routes.GetPointsRequest)
  })
_sym_db.RegisterMessage(GetPointsRequest)

GetPointsResponse = _reflection.GeneratedProtocolMessageType('GetPointsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPOINTSRESPONSE,
  '__module__' : 'protobufs.routes_pb2'
  # @@protoc_insertion_point(class_scope:routes.GetPointsResponse)
  })
_sym_db.RegisterMessage(GetPointsResponse)

GetRoutesRequest = _reflection.GeneratedProtocolMessageType('GetRoutesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETROUTESREQUEST,
  '__module__' : 'protobufs.routes_pb2'
  # @@protoc_insertion_point(class_scope:routes.GetRoutesRequest)
  })
_sym_db.RegisterMessage(GetRoutesRequest)

GetRoutesResponse = _reflection.GeneratedProtocolMessageType('GetRoutesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETROUTESRESPONSE,
  '__module__' : 'protobufs.routes_pb2'
  # @@protoc_insertion_point(class_scope:routes.GetRoutesResponse)
  })
_sym_db.RegisterMessage(GetRoutesResponse)

CalculateRouteRequest = _reflection.GeneratedProtocolMessageType('CalculateRouteRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATEROUTEREQUEST,
  '__module__' : 'protobufs.routes_pb2'
  # @@protoc_insertion_point(class_scope:routes.CalculateRouteRequest)
  })
_sym_db.RegisterMessage(CalculateRouteRequest)

RouteResponse = _reflection.GeneratedProtocolMessageType('RouteResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROUTERESPONSE,
  '__module__' : 'protobufs.routes_pb2'
  # @@protoc_insertion_point(class_scope:routes.RouteResponse)
  })
_sym_db.RegisterMessage(RouteResponse)

CreateRouteRequest = _reflection.GeneratedProtocolMessageType('CreateRouteRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEROUTEREQUEST,
  '__module__' : 'protobufs.routes_pb2'
  # @@protoc_insertion_point(class_scope:routes.CreateRouteRequest)
  })
_sym_db.RegisterMessage(CreateRouteRequest)



_ROUTES = _descriptor.ServiceDescriptor(
  name='Routes',
  full_name='routes.Routes',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=622,
  serialized_end=900,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPoints',
    full_name='routes.Routes.GetPoints',
    index=0,
    containing_service=None,
    input_type=_GETPOINTSREQUEST,
    output_type=_GETPOINTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetRoutes',
    full_name='routes.Routes.GetRoutes',
    index=1,
    containing_service=None,
    input_type=_GETROUTESREQUEST,
    output_type=_GETROUTESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CalculateRoute',
    full_name='routes.Routes.CalculateRoute',
    index=2,
    containing_service=None,
    input_type=_CALCULATEROUTEREQUEST,
    output_type=_ROUTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateRoute',
    full_name='routes.Routes.CreateRoute',
    index=3,
    containing_service=None,
    input_type=_CREATEROUTEREQUEST,
    output_type=_ROUTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTES)

DESCRIPTOR.services_by_name['Routes'] = _ROUTES

# @@protoc_insertion_point(module_scope)
