# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protobufs import routes_pb2 as protobufs_dot_routes__pb2


class RoutesStub(object):
    """service definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPoints = channel.unary_unary(
                '/routes.Routes/GetPoints',
                request_serializer=protobufs_dot_routes__pb2.GetPointsRequest.SerializeToString,
                response_deserializer=protobufs_dot_routes__pb2.GetPointsResponse.FromString,
                )
        self.GetRoutes = channel.unary_unary(
                '/routes.Routes/GetRoutes',
                request_serializer=protobufs_dot_routes__pb2.GetRoutesRequest.SerializeToString,
                response_deserializer=protobufs_dot_routes__pb2.GetRoutesResponse.FromString,
                )
        self.CalculateRoute = channel.unary_unary(
                '/routes.Routes/CalculateRoute',
                request_serializer=protobufs_dot_routes__pb2.CalculateRouteRequest.SerializeToString,
                response_deserializer=protobufs_dot_routes__pb2.RouteResponse.FromString,
                )
        self.CreateRoute = channel.unary_unary(
                '/routes.Routes/CreateRoute',
                request_serializer=protobufs_dot_routes__pb2.CreateRouteRequest.SerializeToString,
                response_deserializer=protobufs_dot_routes__pb2.RouteResponse.FromString,
                )


class RoutesServicer(object):
    """service definitions
    """

    def GetPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoints,
                    request_deserializer=protobufs_dot_routes__pb2.GetPointsRequest.FromString,
                    response_serializer=protobufs_dot_routes__pb2.GetPointsResponse.SerializeToString,
            ),
            'GetRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoutes,
                    request_deserializer=protobufs_dot_routes__pb2.GetRoutesRequest.FromString,
                    response_serializer=protobufs_dot_routes__pb2.GetRoutesResponse.SerializeToString,
            ),
            'CalculateRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateRoute,
                    request_deserializer=protobufs_dot_routes__pb2.CalculateRouteRequest.FromString,
                    response_serializer=protobufs_dot_routes__pb2.RouteResponse.SerializeToString,
            ),
            'CreateRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoute,
                    request_deserializer=protobufs_dot_routes__pb2.CreateRouteRequest.FromString,
                    response_serializer=protobufs_dot_routes__pb2.RouteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routes.Routes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Routes(object):
    """service definitions
    """

    @staticmethod
    def GetPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routes.Routes/GetPoints',
            protobufs_dot_routes__pb2.GetPointsRequest.SerializeToString,
            protobufs_dot_routes__pb2.GetPointsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routes.Routes/GetRoutes',
            protobufs_dot_routes__pb2.GetRoutesRequest.SerializeToString,
            protobufs_dot_routes__pb2.GetRoutesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalculateRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routes.Routes/CalculateRoute',
            protobufs_dot_routes__pb2.CalculateRouteRequest.SerializeToString,
            protobufs_dot_routes__pb2.RouteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/routes.Routes/CreateRoute',
            protobufs_dot_routes__pb2.CreateRouteRequest.SerializeToString,
            protobufs_dot_routes__pb2.RouteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
